name: Release
on:
  push:
    tags:
      - '*'
jobs:
  release:
    name: Release ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, ubuntu-latest ]
    steps:
      - name: Set up Python 3.9.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.8

      - name: Set tag
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project
        run: |
          cd ward
          pip install -r requirements.txt
          pyinstaller ward.spec --onefile --clean --noconfirm

      - uses: papeloto/action-zip@v1
        with:
          files: ward/dist/ward/
          dest: ward-${{ steps.vars.outputs.tag }}-${{matrix.os}}.zip    

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "ward-${{ steps.vars.outputs.tag }}-${{matrix.os}}.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: True
