name: Release
on:
  push:
    tags:
      - '*'
jobs:
  release:
    name: Release ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, ubuntu-latest ]
        build: [root-gar]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Python 3.10.4
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.4

      - name: Set tag
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'

      - name: Package
        run: |
          make pkg-${{ matrix.build }}

#      - name: Set outs
#        id: vars
#        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - uses: ncipollo/release-action@v1
        with:
          artifacts: app/out/make/keep-*${{ outs }}
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: True
